name: sa_somativa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0      
  firebase_auth: ^4.16.0      
  cloud_firestore: ^4.13.0    
  geolocator: ^12.0.0         
  intl: ^0.20.2
  latlong2: ^0.9.1
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true